print("import command packages")
print("import turtle command drawing package, there are many pakages")


import turtle
print("# allows us to use turtle")
wn = turtle.Screen()
print("#Creates a playground for turtle. Not must?")
tut=turtle.Turtle()
print("# Creates aturtle, assign to tut")
tut = turtle.pen()
print("Above, Not must necessary")
tut = turtle.forward(200)
tut = turtle.back(120)
tut = turtle.left(200)
tut = turtle.back(120)
tut = turtle.forward(20)
tut = turtle.left(20)
tut = turtle.forward(120)
tut = turtle.back(120)
tut = turtle.right(20)
tut = turtle.forward(120)
tut = turtle.left(20)
tut = turtle.forward(120)
tut = turtle.right(20)
tut = turtle.forward(120)
tut = turtle.right(20)
tut = turtle.back(120)
tut = wn.mainloop()
print(" Work 'tut = wn.mainloop()' necessary")
