print("import command packages")
print("import turtle command drawing package, there are many pakages")

import turtle
tut = turtle.pen()
tut = turtle.forward(200)
tut = turtle.left(200)
tut = turtle.forward(20)
tut = turtle.left(20)
tut = turtle.forward(120)
tut = turtle.right(20)
tut = turtle.forward(120)
tut = turtle.left(20)
tut = turtle.forward(120)
tut = turtle.right(20)
tut = turtle.forward(120)
tut = turtle.right(20)
tut = turtle.back(120)
quit()